export const SEO_KEYWORDS = [
    // Core Product Keywords
    "terracotta tiles India",
    "clay brick tiles",
    "facing bricks",
    "clay pavers",
    "weathering tiles",
    "roofing tiles",
    "jaali panels",
    "facade tiles",
    "exposed brick tiles",
    "terracotta cladding",
    "architectural tiles",
    "brick wall tiles",
    "terracotta facade panels",
    "clay roof tiles",
    "wirecut bricks",
    "handmade bricks",
    "pressed bricks",
    "clay products",
    "clay building products",
    "architectural clay",
    "low efflorescence tiles",

    // Expanded Product Variants
    "thin brick veneers",
    "hollow clay blocks",
    "porotherm bricks",
    "ventilated facade systems",
    "louvers and baguettes",
    "ceramic wall cladding",
    "fly ash bricks alternative",
    "red clay bricks",
    "antique brick tiles",
    "reclaimed bricks",
    "glazed terracotta",
    "terracotta louvers",
    "rainscreen cladding",

    // Broader Construction & Architecture
    "building facade materials",
    "sustainable construction materials",
    "green building products India",
    "architectural supplies",
    "exterior wall cladding",
    "interior design materials",
    "landscape pavers",
    "patio flooring",
    "elevation tiles design",
    "modern house elevation",
    "traditional indian architecture",
    "vernacular architecture materials",
    "exposed brickwork specs",
    "facade engineering",
    "building envelope solutions",
    "thermal insulation materials",
    "natural cooling materials",
    "leed certified materials",
    "igbc green building products",

    // Location Keywords - Major Cities & States
    "terracotta tiles Mumbai",
    "terracotta tiles Delhi",
    "terracotta tiles Bangalore",
    "terracotta tiles Pune",
    "terracotta tiles Hyderabad",
    "terracotta tiles Chennai",
    "terracotta tiles Kolkata",
    "terracotta tiles Ahmedabad",
    "terracotta tiles Gurgaon",
    "terracotta tiles Noida",
    "construction materials Kerala",
    "brick suppliers Goa",
    "tile showroom Chandigarh",
    "facade contractors Jaipur",
    "architects in Surat",
    "builders in Indore",

    // Application Keywords
    "office facade design",
    "hospitality architecture",
    "resort design materials",
    "cafe interior design",
    "luxury home exterior",
    "villa elevation materials",
    "compound wall cladding",
    "gate design materials",
    "living room wall texture",
    "bedroom feature wall",

    // Professional Keywords
    "architect tiles India",
    "builder resources",
    "contractor supplies",
    "premium clay products",
    "custom terracotta manufacturing",
    "bulk building materials",
    "construction material wholesaler",
    "architectural specification",
    "turnkey facade solutions",
];
