
import { NextRequest, NextResponse } from 'next/server';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { getPaymentLinkDetails } from '@/app/actions/payment-link';

export async function GET(
    request: NextRequest,
    props: { params: Promise<{ orderId: string }> }
) {
    const params = await props.params;

    try {
        const { orderId } = params;
        const { success, order } = await getPaymentLinkDetails(orderId);

        if (!success || !order) {
            return NextResponse.json({ error: 'Order not found' }, { status: 404 });
        }

        // Initialize PDF
        const doc: any = new jsPDF();
        const pageWidth = doc.internal.pageSize.width;

        // --- HEADER ---
        // Brand Name
        doc.setFont("times", "bold");
        doc.setFontSize(28);
        doc.setTextColor(42, 30, 22); // #2A1E16 Dark Brown
        doc.text("UrbanClay", 15, 25);

        // Tagline
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150); // Gray
        doc.text("PREMIUM CLAY SOLUTIONS", 15, 30);

        // Proforma Label
        const isPaid = order.status === 'paid';
        doc.setFont("helvetica", "bold");
        doc.setFontSize(24);
        doc.setTextColor(isPaid ? 42 : 220, isPaid ? 30 : 220, isPaid ? 22 : 220); // Darker if Paid
        doc.text(isPaid ? "TAX INVOICE" : "PROFORMA", pageWidth - 15, 25, { align: 'right' });

        // Meta Info (Right Side)
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`, pageWidth - 15, 35, { align: 'right' });
        doc.text(`${isPaid ? 'Invoice No' : 'Order ID'}: ${isPaid ? (order.zohoInvoiceNumber || order.orderId) : order.orderId}`, pageWidth - 15, 41, { align: 'right' });
        if (order.expiryDate) {
            doc.setTextColor(220, 50, 50); // Red
            doc.text(`Valid Until: ${new Date(order.expiryDate).toLocaleDateString()}`, pageWidth - 15, 47, { align: 'right' });
        }

        // --- CLIENT DETAILS ---
        const startY = 60;

        // Billed To
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text("BILLED TO", 15, startY);

        doc.setFont("times", "bold");
        doc.setFontSize(14);
        doc.setTextColor(42, 30, 22);
        doc.text(order.clientName || "Valued Client", 15, startY + 8);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(80, 80, 80);
        const addressLines = doc.splitTextToSize(order.billingAddress || "", 80);
        doc.text(addressLines, 15, startY + 16);

        // Contact Info
        let currentY = startY + 16 + (addressLines.length * 5) + 5;
        doc.setFontSize(9);
        doc.text(`${order.clientEmail}`, 15, currentY);
        doc.text(`${order.clientPhone}`, 15, currentY + 5);

        if (order.gstNumber) {
            doc.setFont("courier", "bold");
            doc.text(`GST: ${order.gstNumber}`, 15, currentY + 12);
        }

        // --- TABLE ---
        const tableY = currentY + 25;

        const tableData = order.lineItems.map((item: any) => [
            { content: item.name, styles: { fontStyle: 'bold' } },
            item.quantity,
            `Rs. ${item.rate.toLocaleString('en-IN')}`,
            `${item.discount}%`,
            `Rs. ${((item.rate * item.quantity) * (1 - item.discount / 100)).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
        ]);

        (doc as any).autoTable({
            startY: tableY,
            head: [['Item Description', 'Qty', 'Rate', 'Disc', 'Amount']],
            body: tableData,
            theme: 'plain',
            headStyles: {
                fillColor: [250, 250, 250],
                textColor: [150, 150, 150],
                fontStyle: 'bold',
                fontSize: 8,
                halign: 'left'
            },
            bodyStyles: {
                textColor: [42, 30, 22],
                fontSize: 10,
                cellPadding: 6
            },
            columnStyles: {
                0: { cellWidth: 80 },
                4: { halign: 'right', fontStyle: 'bold' }
            },
            didDrawPage: (data: any) => {
                // Footer on every page
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                doc.text("UrbanClay Architecture Pvt Ltd | Generated by Monolith Engine", 15, doc.internal.pageSize.height - 10);
            }
        });

        // --- TOTALS ---
        const finalY = (doc as any).lastAutoTable.finalY + 10;
        const rightAlign = pageWidth - 15;

        // Subtotal
        // We'll calculate totals as they are not stored directly in order object sometimes
        let subtotal = 0;
        let totalDiscount = 0;
        let totalTax = 0;

        order.lineItems.forEach((item: any) => {
            const lineSub = item.rate * item.quantity;
            const lineDisc = lineSub * (item.discount / 100);
            subtotal += lineSub;
            totalDiscount += lineDisc;
            totalTax += (lineSub - lineDisc) * (item.taxRate / 100);
        });

        // Helper for totals row
        const addTotalRow = (label: string, value: string, isBold = false, color = [100, 100, 100]) => {
            doc.setFont("helvetica", isBold ? "bold" : "normal");
            doc.setFontSize(10);
            doc.setTextColor(color[0], color[1], color[2]);
            doc.text(label, rightAlign - 50, currentTotalsY, { align: 'right' });
            doc.text(value, rightAlign, currentTotalsY, { align: 'right' });
            currentTotalsY += 6;
        };

        let currentTotalsY = finalY;

        addTotalRow("Subtotal", `Rs. ${subtotal.toLocaleString('en-IN')}`);
        if (totalDiscount > 0) addTotalRow("Total Discount", `-Rs. ${totalDiscount.toLocaleString('en-IN')}`, false, [50, 160, 100]); // Green
        addTotalRow("Tax (GST)", `Rs. ${totalTax.toLocaleString('en-IN')}`);

        if (order.shippingCharges > 0) {
            addTotalRow("Shipping", `Rs. ${order.shippingCharges.toLocaleString('en-IN')}`);
        }

        if (order.adjustment !== 0) {
            addTotalRow("Adjustment", `Rs. ${order.adjustment.toLocaleString('en-IN')}`);
        }

        // Final Total
        currentTotalsY += 4;
        doc.setLineWidth(0.5);
        doc.setDrawColor(200, 200, 200);
        doc.line(rightAlign - 60, currentTotalsY - 6, rightAlign, currentTotalsY - 6);

        doc.setFont("times", "bold");
        doc.setFontSize(16);
        doc.setTextColor(180, 90, 60); // Terracotta
        doc.text(`Rs. ${order.amount.toLocaleString('en-IN')}`, rightAlign, currentTotalsY, { align: 'right' });
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Total Payable", rightAlign - 60, currentTotalsY, { align: 'right' });


        // --- FOOTER NOTES ---
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text("LOGISTICS & DELIVERY", 15, finalY + 20);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.text(order.deliveryTimeline || "Standard Delivery", 15, finalY + 26);

        if (order.customerNotes) {
            doc.text(order.customerNotes, 15, finalY + 32);
        }

        // Terms
        if (order.terms) {
            const termsY = finalY + 50;
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9);
            doc.setTextColor(150, 150, 150);
            doc.text("TERMS AND CONDITIONS", 15, termsY);

            doc.setFont("courier", "normal");
            doc.setFontSize(8);
            doc.setTextColor(100, 100, 100);
            const termLines = doc.splitTextToSize(order.terms, pageWidth - 30);
            doc.text(termLines, 15, termsY + 6);
        }

        // Generate PDF Buffer
        const pdfBuffer = doc.output('arraybuffer');

        return new NextResponse(pdfBuffer, {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="Proforma_${orderId}.pdf"`
            }
        });

    } catch (error) {
        console.error("PDF Generation Error (Detailed):", error);
        return NextResponse.json({
            error: 'PDF generation failed',
            details: error instanceof Error ? error.message : String(error),
            stack: error instanceof Error ? error.stack : undefined
        }, { status: 500 });
    }
}
